### ISSUE TITLE
Error: Cannot find module 'caniuse-db/features-json/transforms2d.json'

### ISSUE THREAD

**Issue by fightingPie** [superman66/vue2.x-douban#1]
module.js:327
    throw err;
    ^

Error: Cannot find module 'caniuse-db/features-json/transforms2d.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\www\vuenew\vue2.x-douban\node_modules\autoprefixer\data\prefixes.js:113:11)
    at Object.<anonymous> (D:\www\vuenew\vue2.x-douban\node_modules\autoprefixer\data\prefixes.js:655:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by superman66** [comment]
补充下你操作什么出现这个错误。

感觉像是npm 没装好。你可以试试卸载，再重做npm install.

**Comment by LeslieOA** [comment]
Google translation of @superman66's comment above:

> Add what you are doing with this error.
> 
> Feeling like npm not installed. You can try uninstalling and redo `npm install` again.

**Comment by MMPickMe** [comment]
Is that solved now,I had this problem,npm install is not having any effect
